# Generated by Django 6.0.5 on 2026-05-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('appetizers', 'Закуски'), ('main_courses', 'Основні страви'), ('seafood', 'Морські страви'), ('drinks', 'Напої'), ('desserts', 'Десерти')], default='main_courses', max_length=20, verbose_name='Категорія'),
        ),
    ]
